run:
  compute_stress: True
  compute_device: 0
  graphics_device: 0
  fps: 60
  headless: False
  num_envs: 1
  robot: franka
  save_img: False
  save_fps: 5
  seed: 0
  soft: cylinder
  substeps: 3
  timeout: 100
  use_gpu_pipeline: False
  viz_stress: True
  viz_stress_min: 0
  viz_stress_max: 5000

dir:
  asset: data/assets/urdf
  log: logs

object:
  franka:
    path: franka_description/robots/franka_panda.urdf
    angular_damping: 100.0
    armature: 0.01
    disable_gravity: True
    fix_base_link: True
    flip_visual_attachments: True
    linear_damping: 1.0
    max_linear_velocity: 0.01
    override_inertia: True
    thickness: 0.0
    use_mesh_materials: True
    # default_dof_drive_mode: gymapi.DOF_MODE_POS

  kinova:
    path: kinova_description/urdf/kinova.urdf
    angular_damping: 100.0
    armature: 0.0
    disable_gravity: False
    fix_base_link: True
    flip_visual_attachments: True
    linear_damping: 1.0
    max_linear_velocity: 0.01
    override_inertia: True
    thickness: 0.0
    use_mesh_materials: True

  psm:
    path: "psm/psm.urdf"
    angular_damping: 100.0
    armature: 0.0
    disable_gravity: False
    fix_base_link: True
    flip_visual_attachments: False
    linear_damping: 1.0
    max_linear_velocity: 0.01
    thickness: 0.1
    use_mesh_materials: True
    # default_dof_drive_mode: gymapi.DOF_MODE_POS

  ant:
    path: nv_ant/nv_ant.xml
    armature: 0.0
    disable_gravity: False
    fix_base_link: True
    flip_visual_attachments: False
    linear_damping: 1.0
    max_linear_velocity: 0.01
    thickness: 0.1
    use_mesh_materials: True

  hemisphere:
    path: hemisphere_010/hemishere_010.urdf
    fix_base_link: True
    thickness: 0.1
    min_particle_mass: 0.1

  tissue:
    path: tissue/tissue.urdf
    fix_base_link: True
    thickness: 0.1
    min_particle_mass: 0.1

  intestine:
    path: intestine/intestine.urdf
    fix_base_link: True
    thickness: 0.1
    armature: 0.1
    min_particle_mass: 0.1
    override_inertia: True
    override_com: True

  cylinder:
    path: cylinder/cylinder.urdf
    disable_gravity: False
    fix_base_link: True
    thickness: 0.1
    armature: 0.1
    min_particle_mass: 0.1

  icosphere:
    path: icosphere/icosphere.urdf
    fix_base_link: True
    thickness: 0.1

flex:
  solver_type: 5
  num_outer_iterations: 4
  num_inner_iterations: 20
  relaxation: 0.8
  warm_start: 0.75
  shape_collision_margin: 0.1

cam:
  width: 1920
  height: 1080
  use_collision_geometry: False
  position: [0.7, 1.4, 1.8]
  target: [-0.4, 0.2, 0]

soft_material:
  activation: 0.1
  activationMax: 0.3
  damping: 0.0
  model: neo
  poissons: 0.3
  youngs: 10000000.0

hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - _self_
