# FROM nvcr.io/nvidia/pytorch:21.12-py3
# FROM nvcr.io/nvidia/pytorch:18.05-py3
FROM nvidia/cuda:9.2-devel-ubuntu16.04

LABEL maintainer="kostonerx@gmail.com"

ARG TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    cmake \
    build-essential \
    libgl1-mesa-dev \
    freeglut3-dev \
    libglfw3-dev \
    libgles2-mesa-dev \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
SHELL ["/bin/bash", "-c"]

RUN wget https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh \
    && bash Anaconda3-2021.11-Linux-x86_64.sh -b -p /opt/anaconda3 \
    && rm Anaconda3-2021.11-Linux-x86_64.sh

ARG ENV_NAME=softgym
COPY environment.yml .

RUN pip install --upgrade pip \
    && conda update -n base -c defaults conda && \
    conda env create -n ${ENV_NAME} -f environment.yml && \
    conda init && \
    echo "conda activate ${ENV_NAME}" >> ~/.bashrc

ENV CONDA_DEFAULT_ENV ${ENV_NAME}
ENV PATH /opt/conda/envs/${ENV_NAME}/bin:$PATH
ENV PYFLEXROOT=/workspace/softgym/PyFlex
ENV PYTHONPATH=${PYFLEXROOT}/bindings/build:$PYTHONPATH
ENV LD_LIBRARY_PATH=${PYFLEXROOT}/external/SDL2-2.0.4/lib/x64:$LD_LIBRARY_PATH
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute

SHELL ["conda", "run", "-n", "${ENV_NAME}", "/bin/bash", "-c"]

# RUN conda install -y -q \
#     anaconda \
#     click \
#     cython \
#     imageio \
#     joblib \
#     matplotlib \
#     Pillow \
#     plotly \
#     pybind11 \
#     && conda update --all && conda clean -a -y -q

# RUN pip install \
#     gtimer \
#     gym \
#     moviepy \
#     opencv-python \
#     pyquaternion \
#     Shapely \
#     sk-video

WORKDIR /workspace

CMD ["/bin/bash"]
