version: "3"
services:
  sim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adhesiolysis
    volumes:
      - ../:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8888:8888"
    restart: always
    tty: true
    # # Comment out the following line when using CPU-only mode
    # deply:
    #   resouces:
    #     reservations:
    #       devices:
    #         - drive: nvidia
    #           count: 1 #or e.g., -device_ids:['0', '1']
    #           capability: [ gpu ]
