version: "3"
services:
  sim:
    build:
      context: .
      dockerfile: Dockerfile
    image: ksterx/surgym
    container_name: surgym
    volumes:
      - ../:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8888:8888"
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    restart: always
    tty: true
    # # Comment out the following line when using CPU-only mode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
